--Начальное заполнение БД. типы и справочники
SET IDENTITY_INSERT [dbo].[MainObjects] ON
INSERT INTO [dbo].[MainObjects] ([Id], [ParentId], [TypeId], [Value], [Weight], [HasChildrens], [DueCode]) VALUES (1, 1, 2, N'Root', 100, 0, N'0.')
INSERT INTO [dbo].[MainObjects] ([Id], [ParentId], [TypeId], [Value], [Weight], [HasChildrens], [DueCode]) VALUES (2, 0, 2, N'text', 100, 0, NULL)
INSERT INTO [dbo].[MainObjects] ([Id], [ParentId], [TypeId], [Value], [Weight], [HasChildrens], [DueCode]) VALUES (3, 0, 3, N'number', 200, 0, NULL)
INSERT INTO [dbo].[MainObjects] ([Id], [ParentId], [TypeId], [Value], [Weight], [HasChildrens], [DueCode]) VALUES (4, 0, 2, N'Комплекс', 0, 0, NULL)
INSERT INTO [dbo].[MainObjects] ([Id], [ParentId], [TypeId], [Value], [Weight], [HasChildrens], [DueCode]) VALUES (5, 4, 2, N'Размещение', 100, 0, NULL)
INSERT INTO [dbo].[MainObjects] ([Id], [ParentId], [TypeId], [Value], [Weight], [HasChildrens], [DueCode]) VALUES (6, 4, 2, N'Назначение', 200, 0, NULL)
INSERT INTO [dbo].[MainObjects] ([Id], [ParentId], [TypeId], [Value], [Weight], [HasChildrens], [DueCode]) VALUES (7, 4, 3, N'Мощность, кВт', 300, 0, NULL)
INSERT INTO [dbo].[MainObjects] ([Id], [ParentId], [TypeId], [Value], [Weight], [HasChildrens], [DueCode]) VALUES (8, 4, 3, N'Вес, кг', 400, 0, NULL)
INSERT INTO [dbo].[MainObjects] ([Id], [ParentId], [TypeId], [Value], [Weight], [HasChildrens], [DueCode]) VALUES (9, 0, 2, N'Узел', 0, 0, NULL)
INSERT INTO [dbo].[MainObjects] ([Id], [ParentId], [TypeId], [Value], [Weight], [HasChildrens], [DueCode]) VALUES (10, 9, 2, N'Тип', 100, 0, NULL)
INSERT INTO [dbo].[MainObjects] ([Id], [ParentId], [TypeId], [Value], [Weight], [HasChildrens], [DueCode]) VALUES (11, 9, 2, N'Категория', 200, 0, NULL)
INSERT INTO [dbo].[MainObjects] ([Id], [ParentId], [TypeId], [Value], [Weight], [HasChildrens], [DueCode]) VALUES (12, 9, 3, N'Производительность', 300, 0, NULL)
INSERT INTO [dbo].[MainObjects] ([Id], [ParentId], [TypeId], [Value], [Weight], [HasChildrens], [DueCode]) VALUES (13, 0, 2, N'Установка', 0, 0, NULL)
INSERT INTO [dbo].[MainObjects] ([Id], [ParentId], [TypeId], [Value], [Weight], [HasChildrens], [DueCode]) VALUES (14, 13, 2, N'Марка', 100, 0, NULL)
INSERT INTO [dbo].[MainObjects] ([Id], [ParentId], [TypeId], [Value], [Weight], [HasChildrens], [DueCode]) VALUES (15, 13, 2, N'Модель', 200, 0, NULL)
INSERT INTO [dbo].[MainObjects] ([Id], [ParentId], [TypeId], [Value], [Weight], [HasChildrens], [DueCode]) VALUES (16, 13, 2, N'Производитель', 300, 0, NULL)
INSERT INTO [dbo].[MainObjects] ([Id], [ParentId], [TypeId], [Value], [Weight], [HasChildrens], [DueCode]) VALUES (17, 13, 3, N'Глубина, м', 400, 0, NULL)
INSERT INTO [dbo].[MainObjects] ([Id], [ParentId], [TypeId], [Value], [Weight], [HasChildrens], [DueCode]) VALUES (18, 0, 2, N'Насос', 0, 0, NULL)
INSERT INTO [dbo].[MainObjects] ([Id], [ParentId], [TypeId], [Value], [Weight], [HasChildrens], [DueCode]) VALUES (19, 18, 2, N'Марка', 100, 0, NULL)
INSERT INTO [dbo].[MainObjects] ([Id], [ParentId], [TypeId], [Value], [Weight], [HasChildrens], [DueCode]) VALUES (20, 18, 3, N'Напор, бар', 200, 0, NULL)
INSERT INTO [dbo].[MainObjects] ([Id], [ParentId], [TypeId], [Value], [Weight], [HasChildrens], [DueCode]) VALUES (21, 18, 3, N'Вес, кг', 300, 0, NULL)
INSERT INTO [dbo].[MainObjects] ([Id], [ParentId], [TypeId], [Value], [Weight], [HasChildrens], [DueCode]) VALUES (22, 0, 2, N'Деталь', 0, 0, NULL)
INSERT INTO [dbo].[MainObjects] ([Id], [ParentId], [TypeId], [Value], [Weight], [HasChildrens], [DueCode]) VALUES (23, 22, 2, N'Тип', 100, 0, NULL)
INSERT INTO [dbo].[MainObjects] ([Id], [ParentId], [TypeId], [Value], [Weight], [HasChildrens], [DueCode]) VALUES (24, 22, 2, N'Материал', 200, 0, NULL)
INSERT INTO [dbo].[MainObjects] ([Id], [ParentId], [TypeId], [Value], [Weight], [HasChildrens], [DueCode]) VALUES (25, 22, 2, N'Артикул', 300, 0, NULL)
INSERT INTO [dbo].[MainObjects] ([Id], [ParentId], [TypeId], [Value], [Weight], [HasChildrens], [DueCode]) VALUES (26, 22, 3, N'Вес, кг', 400, 0, NULL)
INSERT INTO [dbo].[MainObjects] ([Id], [ParentId], [TypeId], [Value], [Weight], [HasChildrens], [DueCode]) VALUES (27, 22, 3, N'Объем, л', 500, 0, NULL)
SET IDENTITY_INSERT [dbo].[MainObjects] OFF
